(cl:defpackage navigation-srv
  (:use )
  (:export
   "GETRELEVANTPOSITION"
   "<GETRELEVANTPOSITION-REQUEST>"
   "GETRELEVANTPOSITION-REQUEST"
   "<GETRELEVANTPOSITION-RESPONSE>"
   "GETRELEVANTPOSITION-RESPONSE"
  ))

