TrajectoryPlannerROS: 
  max_vel_x: 3
  min_vel_x: 0.6
  max_rotational_vel: 2
  min_in_place_rotational_vel: 0.4
  min_in_place_vel_theta: 1
  max_vel_theta: 2
  min_vel_theta: -2
  acc_lim_th: 3.2 
  acc_lim_x: 2.5 
  acc_lim_y: 0 
  holonomic_robot: false 