max_obstacle_height: 0.60
obstacle_range: 5
raytrace_range: 8

robot_radius: 0.27

inflation_radius: 0.31
cost_scaling_factor: 10

map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 2
publish_voxel_map: false

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true, observation_persistence: 0.0}
