global_frame: map
robot_base_frame: base_link

max_obstacle_height: 0.60
obstacle_range: 5
raytrace_range: 8

robot_radius: 0.28

inflation_radius: 0.31
cost_scaling_factor: 6.0

map_type: voxel

obstacle_layer:
    origin_z: -0.1
    z_resolution: 0.5 #1.5 This must be higher than the z coordinate of the mounted lidar
    z_voxels: 1 
    obstacle_range: 8.0 #10.0
    raytrace_range: 8.0 #15.0
    observation_sources: laser_scan_sensor
    track_unknown_space: false
    lethal_cost_threshold: 100
    unknown_cost_value: 2 

    laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true, min_obstacle_height: 0.00, max_obstacle_height: 3.00}

inflation_layer:
    enabled: true
    cost_scaling_factor: 6.0 #added in by John
    inflation_radius: 0.31 #0.45 #Minimum value: 0.379