local_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 8.0
   publish_frequency: 0.5
   static_map: false
   rolling_window: true
   width: 8.0
   height: 8.0
   resolution: 0.05
   transform_tolerance: 0.5