shutdown_costmaps: false

controller_frequency: 8
controller_patience: 8.0

planner_frequency: 8
planner_patience: 10.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

base_local_planner: "teb_local_planner/TebLocalPlannerROS"
base_global_planner: "navfn/NavfnROS"

recovery_behavior_enabled: true

recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'

conservative_reset:
  reset_distance: 0.0
  layer_names: ["obstacle_layer", "inflation_layer"]

aggressive_reset:
  reset_distance: 0.0
  layer_names: ["obstacle_layer", "inflation_layer"]