// Generated by gencpp from file navigation/custom_msg.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_CUSTOM_MSG_H
#define NAVIGATION_MESSAGE_CUSTOM_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct custom_msg_
{
  typedef custom_msg_<ContainerAllocator> Type;

  custom_msg_()
    : id(0)
    , message()  {
    }
  custom_msg_(const ContainerAllocator& _alloc)
    : id(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::navigation::custom_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::custom_msg_<ContainerAllocator> const> ConstPtr;

}; // struct custom_msg_

typedef ::navigation::custom_msg_<std::allocator<void> > custom_msg;

typedef boost::shared_ptr< ::navigation::custom_msg > custom_msgPtr;
typedef boost::shared_ptr< ::navigation::custom_msg const> custom_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::custom_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::custom_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::custom_msg_<ContainerAllocator1> & lhs, const ::navigation::custom_msg_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::custom_msg_<ContainerAllocator1> & lhs, const ::navigation::custom_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::navigation::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "057c93aa7db5ff04c6ea0d81ef773307";
  }

  static const char* value(const ::navigation::custom_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x057c93aa7db5ff04ULL;
  static const uint64_t static_value2 = 0xc6ea0d81ef773307ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/custom_msg";
  }

  static const char* value(const ::navigation::custom_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::navigation::custom_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::custom_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::custom_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::custom_msg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_CUSTOM_MSG_H
