// Generated by gencpp from file navigation/GetRelevantPositionResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GETRELEVANTPOSITIONRESPONSE_H
#define NAVIGATION_MESSAGE_GETRELEVANTPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct GetRelevantPositionResponse_
{
  typedef GetRelevantPositionResponse_<ContainerAllocator> Type;

  GetRelevantPositionResponse_()
    : status(false)  {
    }
  GetRelevantPositionResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRelevantPositionResponse_

typedef ::navigation::GetRelevantPositionResponse_<std::allocator<void> > GetRelevantPositionResponse;

typedef boost::shared_ptr< ::navigation::GetRelevantPositionResponse > GetRelevantPositionResponsePtr;
typedef boost::shared_ptr< ::navigation::GetRelevantPositionResponse const> GetRelevantPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::GetRelevantPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::GetRelevantPositionResponse_<ContainerAllocator1> & lhs, const ::navigation::GetRelevantPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::GetRelevantPositionResponse_<ContainerAllocator1> & lhs, const ::navigation::GetRelevantPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::navigation::GetRelevantPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/GetRelevantPositionResponse";
  }

  static const char* value(const ::navigation::GetRelevantPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::navigation::GetRelevantPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRelevantPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::GetRelevantPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::GetRelevantPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_GETRELEVANTPOSITIONRESPONSE_H
