// Generated by gencpp from file navigation/GetRelevantPosition.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GETRELEVANTPOSITION_H
#define NAVIGATION_MESSAGE_GETRELEVANTPOSITION_H

#include <ros/service_traits.h>


#include <navigation/GetRelevantPositionRequest.h>
#include <navigation/GetRelevantPositionResponse.h>


namespace navigation
{

struct GetRelevantPosition
{

typedef GetRelevantPositionRequest Request;
typedef GetRelevantPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRelevantPosition
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::GetRelevantPosition > {
  static const char* value()
  {
    return "29c913f5cf74fb9a7ace0f16e99a4a40";
  }

  static const char* value(const ::navigation::GetRelevantPosition&) { return value(); }
};

template<>
struct DataType< ::navigation::GetRelevantPosition > {
  static const char* value()
  {
    return "navigation/GetRelevantPosition";
  }

  static const char* value(const ::navigation::GetRelevantPosition&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::GetRelevantPositionRequest> should match
// service_traits::MD5Sum< ::navigation::GetRelevantPosition >
template<>
struct MD5Sum< ::navigation::GetRelevantPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::GetRelevantPosition >::value();
  }
  static const char* value(const ::navigation::GetRelevantPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GetRelevantPositionRequest> should match
// service_traits::DataType< ::navigation::GetRelevantPosition >
template<>
struct DataType< ::navigation::GetRelevantPositionRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::GetRelevantPosition >::value();
  }
  static const char* value(const ::navigation::GetRelevantPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::GetRelevantPositionResponse> should match
// service_traits::MD5Sum< ::navigation::GetRelevantPosition >
template<>
struct MD5Sum< ::navigation::GetRelevantPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::GetRelevantPosition >::value();
  }
  static const char* value(const ::navigation::GetRelevantPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GetRelevantPositionResponse> should match
// service_traits::DataType< ::navigation::GetRelevantPosition >
template<>
struct DataType< ::navigation::GetRelevantPositionResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::GetRelevantPosition >::value();
  }
  static const char* value(const ::navigation::GetRelevantPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_GETRELEVANTPOSITION_H
