// Generated by gencpp from file navigation/GetRelevantPositionRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GETRELEVANTPOSITIONREQUEST_H
#define NAVIGATION_MESSAGE_GETRELEVANTPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct GetRelevantPositionRequest_
{
  typedef GetRelevantPositionRequest_<ContainerAllocator> Type;

  GetRelevantPositionRequest_()
    : relevantposition(0)  {
    }
  GetRelevantPositionRequest_(const ContainerAllocator& _alloc)
    : relevantposition(0)  {
  (void)_alloc;
    }



   typedef int32_t _relevantposition_type;
  _relevantposition_type relevantposition;





  typedef boost::shared_ptr< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetRelevantPositionRequest_

typedef ::navigation::GetRelevantPositionRequest_<std::allocator<void> > GetRelevantPositionRequest;

typedef boost::shared_ptr< ::navigation::GetRelevantPositionRequest > GetRelevantPositionRequestPtr;
typedef boost::shared_ptr< ::navigation::GetRelevantPositionRequest const> GetRelevantPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::GetRelevantPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::GetRelevantPositionRequest_<ContainerAllocator1> & lhs, const ::navigation::GetRelevantPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.relevantposition == rhs.relevantposition;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::GetRelevantPositionRequest_<ContainerAllocator1> & lhs, const ::navigation::GetRelevantPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06e83fb247ed357d986ea47c3a75b19a";
  }

  static const char* value(const ::navigation::GetRelevantPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06e83fb247ed357dULL;
  static const uint64_t static_value2 = 0x986ea47c3a75b19aULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/GetRelevantPositionRequest";
  }

  static const char* value(const ::navigation::GetRelevantPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 relevantposition\n"
;
  }

  static const char* value(const ::navigation::GetRelevantPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.relevantposition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRelevantPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::GetRelevantPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::GetRelevantPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "relevantposition: ";
    Printer<int32_t>::stream(s, indent + "  ", v.relevantposition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_GETRELEVANTPOSITIONREQUEST_H
